[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "python-toolbox"
version = "0.1.0"
description = "A multi-tab toolbox application with extensible plugins."
requires-python = ">=3.13"
dependencies = [
    "PySide6",
]
